### ISSUE TITLE
Document route tracker

### ISSUE THREAD

**Issue by EwoutH** [EwoutH/shipping-data#14]
Improve documentation of the routescanner
- [ ] Create overview document with the files and functions used
 - [ ] Document specific things about the routescanner search and data collected
 - [ ] Sync and document notebook
 - [ ] Update comments

**Comment by EwoutH** [comment]
The old Routescanner (v1) webscraper is documented in [the Readme](https://github.com/EwoutH/shipping-data#routescanner).
